### ISSUE TITLE
adding images

### ISSUE THREAD

**Issue by Tactile-electronics** [DoESLiverpool/WearableTechBadgeWorkshop#1]

**Comment by Tactile-electronics** [comment]
![image 1](https://user-images.githubusercontent.com/8654515/72371763-efbcae80-36fc-11ea-8d14-13dd224ededc.jpg)
![image 2](https://user-images.githubusercontent.com/8654515/72371771-f0eddb80-36fc-11ea-990e-8f0d262bd25a.jpg)
![image 3](https://user-images.githubusercontent.com/8654515/72371783-f5b28f80-36fc-11ea-9aa2-93fa34d648ef.jpg)
![Image 4](https://user-images.githubusercontent.com/8654515/72371788-f77c5300-36fc-11ea-9b14-b43e24a24b3f.jpg)
![Image 5](https://user-images.githubusercontent.com/8654515/72371789-f8ad8000-36fc-11ea-8e0a-334231272d38.jpg)
![Image 6](https://user-images.githubusercontent.com/8654515/72371791-f9dead00-36fc-11ea-9184-d17322443f5c.jpg)
![Image 7](https://user-images.githubusercontent.com/8654515/72371792-fba87080-36fc-11ea-88c5-f606972d1abc.jpg)
![Image 8](https://user-images.githubusercontent.com/8654515/72371794-fcd99d80-36fc-11ea-9517-2dbd8afebe98.jpg)
![image 9](https://user-images.githubusercontent.com/8654515/72371797-fea36100-36fc-11ea-9f42-789dc24dbb6a.jpg)

**Comment by cheapjack** [comment]
Keeping open because this is just a handy temporary place to host the pictures of Lauras. We can move them into the repo proper later
