### ISSUE TITLE
Sort out the remaining things to do for session 3

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/WearableTechBadgeWorkshop#3]
- [x] Change the example code for 7 LED  Neopixel circles @cheapjack 
- [x] Solder headers onto the 7 LED Neopixel cirlces @jackie1050
- [x] Check we have all the battery related stuff @cheapjack
- [ ] Source Switches @cheapjack  
- [x] mini USB lipo Battery charger - solder on headers @jackie1050
- [ ] solder headers onto the correct male JST leads so the smaller 600mah drone batteries are compatible with the miniUSB Battery chargers
- [ ] source more mini usb cables
- [x] check we can use drone batteries with the miniUSB lipo chargers
- [x] check the tutorial including pressing button while flashing
- [x] test & label data cables
- [x] acquire 2 more drone batteries @cheapjack

**Comment by cheapjack** [comment]
Can't find my switches so we'll have to do without and only managed to secure 3 mini USBs for the chargers. People will have to source their own.

**Comment by cheapjack** [comment]
Sourced enough headers for soldering tomorrow

**Comment by JackiePease** [comment]
Soldered the circles and Lipo chargers before the previous comment was added!
I didn't have a set of male to female dupont connectors, and have had to cut female ends from the headers in order to use female to female ones in some cases (not ideal).

**Comment by JackiePease** [comment]
I can buy some more poppers tomorrow to use as switches
